### ISSUE TITLE
Read the description :)

### ISSUE THREAD

**Issue by CarlosBellange** [Gerschtli/manage-packages#22]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Home
**Thrown From**: [manage-packages](https://github.com/Gerschtli/manage-packages) package 0.3.5

### Stack Trace

Failed to activate the manage-packages package

```
At Unexpected identifier

C:\Users\bellangegalleri2\.atom\packages\manage-packages\lib\util.js:12
  }sourceMappingURL
   ^^^^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:84:7)
    at NativeCompileCache.runInThisContext (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:148814)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149668)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149207)
    at /packages/manage-packages/lib/apm.js:3:39)
    at /packages/manage-packages/lib/apm.js:60:2)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149891)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149207)
    at /packages/manage-packages/lib/list.js:5:26)
    at /packages/manage-packages/lib/list.js:59:2)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149891)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149207)
    at /packages/manage-packages/lib/manage-packages.js:4:41)
    at /packages/manage-packages/lib/manage-packages.js:55:2)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149891)
```

### Commands

```
     -7:31.7.0 core:copy (span.syntax--text.syntax--plain.syntax--null-grammar)
  6x -7:07.9.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-clock 0.1.18 
atom-haskell 0.4.0 
atom-haskell-hie 0.5.0 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atomiix 1.7.1 
busy-signal 2.0.1 
enable-packages 1.4.6 
haskell-pointfree 0.2.0 
haskell-scry 1.0.9 
hasklig 0.4.0 
hey-pane 1.2.0 
Hydrogen 2.16.3 
hydrogen-run 0.1.13 
ide-haskell 2.7.0 
ide-haskell-cabal 2.6.1 
ide-haskell-hasktags 0.0.17 
ide-haskell-hie 0.12.0 
ide-haskell-hoogle 0.1.3 
ide-haskell-repl 0.11.1 
intentions 2.1.1 
language-haskell 1.23.0 
language-maml 0.3.1 
linter 3.4.0 
linter-ui-default 3.4.1 
manage-packages 0.3.5 
medium-export 0.4.0 
my-package 0.0.0 
my-theme-syntax 0.0.0 
packages-txt 0.2.2 
scroll-through-time 0.3.1 
skew 0.1.5 
teletype 0.13.4 
zentabs 0.8.9 
```

**Comment by CarlosBellange** [comment]
Be aware that this content doesnt activate and has a hook.
